### ISSUE TITLE
twitter ripping not working

### ISSUE THREAD

**Issue by version365** [4pr0n/ripme#207]
I am trying to rip [this twitter account](https://twitter.com/carloss75648966)
but it's not ripping anything.. says rip complete but nothing is there..

[log](http://pastebin.com/JKWGM4nh)

**Comment by metaprime** [comment]
It looks like that account did not post any media, but merely retweeted a lot of other content. Maybe you were expecting the content from the retweeted tweets to be ripped?

Since the Twitter ripper seems to be working as expected, I'm going to close this issue. However I'll open a new one to request support for ripping retweeted content.
