### ISSUE TITLE
500px not downloading largest size and adding watermark

### ISSUE THREAD

**Issue by anonimo402** [4pr0n/ripme#260]
This photo for example: https://500px.com/photo/125562869/dark-wasteland-by-michael-goh

The program downloads from this url:
https://drscdn.500px.org/photo/125562869/m%3D1170_k%3D1_a%3D1/16a8db6d2b2f37cec35a3e588888108b

The largest size is here:
https://drscdn.500px.org/photo/125562869/m%3D2048/5f5471e71a3e3583730f0ed2fc9920eb

**Comment by 4pr0n** [comment]
This is because RipMe is using 500px's API. From the [docmentation on image sizes](https://github.com/500px/api-documentation/blob/master/basics/formats_and_terms.md#image-urls-and-image-sizes):

> The images provided with our standard API access will be watermarked with the 500px logo and attribution. For non-watermarked images please contact sales@500px.com

Which I assume means it costs money to get non-watermarked, higher-res images.

But there's probably a workaround...

**Comment by Hrxn** [comment]
Well, I have a userscript for 500px: https://github.com/Hrxn/Userscripts/blob/master/500px.user.js

So, yes, you can get images with higher resolution.
You can use this userscript with either Firefox and Greasemonkey, or any Chrome(ium) browser and Tampermonkey.
It should also work without any extension, just paste all that JS code into the browser console and run it. 
I have tested this on Chrome, this works. Chrome also has a nice feature to save "snippets", custom pieces of JS to easily run whenever and wherever you want. This might sound complicated, but it is actually really [easy to use](https://developers.google.com/web/tools/chrome-devtools/debug/snippets/?hl=en).

Simply run the script on any `*://500px.com/photo/*` page, you can just navigate normally now, so click the left or right arrow, or use the left or right key and use the links on the right side that are now appearing.

There are some caveats though: 
This script uses MutationObserver to monitor changes to the document body, and that can be flaky at times. It works fine for the purpose, i.e. when browsing the site you can always get the link for the image you are currently viewing.

But the 'try download' link only works in Chrome(ium) browsers, I have no idea why. It uses the `download=""` attribute in the <a element, maybe they don't work at all in Firefox, even if it is part of the official spec. And the changing of the file name does not work as well, I'm trying to do `downoad="' + filename '"`, this should work theoretically, that is part of the [HTML Standard](http://www.w3.org/TR/html5/links.html#attr-hyperlink-download), but maybe the HTTP Response can override this. Maybe I should ask on Stack overflow, if someone knows stuff they are there ;-)

Anyway, the real interesting part is the `m%3D2048`bit in an URL that indicates the biggest size available. Sometimes you have photo pages with `m%3D2048_k%(Something)`, this means that the picture will be in a bigger size but it still has '500px' watermarks. But I think that there can't be done anything in this cases, because you only have these links with `m%3D2048_k%(Something)` and nothing else. No other image publicly accessible at their servers.

But finding these links is pretty easy, actually. Open just any single 500px photo page, view the source (They disabled right-click and I haven't found out how to circumvent this, but you can always use `Ctrl+U`of course) and search for `m%3D2048`. You will always find 6 links in different parts of that page.

1.
```HTML
<meta content='https://drscdn.500px.org/photo/80626185/m%3D2048/9d821f61feb3aab9fb69c3bef2592ec6' property='og:image'>
```
2.
```HTML
<meta content='https://drscdn.500px.org/photo/80626185/m%3D2048/9d821f61feb3aab9fb69c3bef2592ec6' property='twitter:image:src'>
```

3.
3 - 5
Also inside the <head
```HTML
<script>
  window.PxPreloadedData = (Bunch of JSON)
</script>
```
The links are encoded here, i.e. slashes are escaped with `\/`

6.
Inside the <body now
```HTML
<div id='preload' style='display: none'>
<img src='https://drscdn.500px.org/photo/80626185/m%3D2048/9d821f61feb3aab9fb69c3bef2592ec6'>
</div>
```

I've looked at a lot of these links now, on many different photos, and apparently it is always the same link, six times. Please tell me if you spot any difference...

So, theoretically, for every `https://500px.com/photo/(PHOTO-ID)/(PHOTO-TITLE)` you will get the same HTML source, and the links inside of the <meta section and the <div id='preload' should be relatively easy to access. If you load a photo page this way, by direct link, it should always work. I have not found any deviant behaviour here so far.

Of course, the golden question is, what about a gallery page, or a profile page, like this one: https://500px.com/lenin1968

Well, all the images there are linked in this way:
https://500px.com/photo/< ID >/< TITLE >

I guess it should be possible, somehow ;-)

Caveat II:

https://marketplace.500px.com/ is entirely a different story

Caveat III:

The REAL, full-size images (originals, maybe RAW), with dimensions of a couple megapixels (as listed in the section at the right, Details, Download, or Purchase) are not accessible via the public web, I would bet. 500px has them on their servers, but you will only get them if you really purchase them, I assume.

Also, please keep in mind:

During my tests, the links in the format listed above always worked, so you will always get an image via URL, but some photographers do not upload images in a high resolution, that is their discretion. So don't be surprised when you use such a link but the image you end up with is rather 'small'

;-) 

If anyone has more questions, please let me know,
If I can be of any help with testing, please let me know as well..

**Comment by 4pr0n** [comment]
I looked into this; looks like the site uses some clever javascript to call 500px's API using a CONSUMER_KEY that has higher privileges than a free API account (which RipMe uses). This explains why you can get non-watermarked, higher-res images via their website (using Chrome/Firefox) than via RipMe.

Luckily the photo page (e.g. `https://500px.com/photo/125562869/dark-wasteland-by-michael-goh`) has a link to the full-size, non-watermarked image. Downloading is a lot slower now, but it gets the full image.
