### ISSUE TITLE
--rerip

### ISSUE THREAD

**Issue by jackusm** [4pr0n/ripme#262]
As (I think) it downloads newer images first could we maybe get a option for -r to skip the current album when a certain number of files are skipped?

**Comment by metaprime** [comment]
Depending on the site, sometimes new content is added at the beginning, and sometimes at the end. I think the logic for this would need to be per-site rather than everything.

Logic per-ripper could also be improved to check for new content more quickly rather than visiting every image.

Of course, enhancements like saving a list of URLs that have already been ripped would help a lot with skipping over already-ripped content.

I'm going to mark this issue as won't fix because there's nothing specific to action on here, but there are definitely improvements to be made in general.
