### ISSUE TITLE
Imagefap changed their site design. So, imagefap ripper no longer works.

### ISSUE THREAD

**Issue by version365** [4pr0n/ripme#271]
imagefap changed their website design. The images are now stored as per uploader directory. 
Modify the ripper.. (whenever possible).

**Comment by masteraaran** [comment]
Can you give a bit more info for how/when you get an error? I just tested it on a gallery/album and it worked fine...

**Comment by snasnasna** [comment]
It only seems to download thumbnails, not the full images.

Seemed to work until yesterday for me, though..?

**Comment by h3aso4** [comment]
I'll try to summarize what's now happening since the imagefap change. I hope it makes sense. When you copy a link from the main page, or a list of galleries, it's now downloading the thumbnails.  If, however, you click on a particular gallery, then copy that gallery url to the clipboard (which is different than the link you previously selected, this is what's changed on imagefap), then it will download the full sized pictures.

**Comment by 4pr0n** [comment]
I can't reproduce. Can you provide a link to a URL that the ripper isn't working properly for?

**Comment by h3aso4** [comment]
I'll try. Here's one that my proved my previous comment wrong and insists on downloading the thumbnails from the gallery regardless of which link you use to try to download the gallery from (whether its the link from the main gallery listing/user's gallery listing, or even the actual gallery link where you're viewing the pictures in that particular gallery).

http://www.imagefap.com/pictures/5851685/The-Ass-the-best-part-of-a-woman-162

**Comment by 4pr0n** [comment]
Thanks for the examples. Looks like it has to do with a new hosting domain imagefap is using; luckily the URL to the full-size image can still be derived from the thumbnail URL.

Updated in v1.2.2
