### ISSUE TITLE
Tumblr: will rip the whole site instead of just tagged files if /tagged/ is not in the url

### ISSUE THREAD

**Issue by cm-mc** [4pr0n/ripme#275]
Most of the times this can be worked around by manually adding /tagged/ to the url, unfortunately that's not always the case, as in this example: http://sexualsensualmenagerie.tumblr.com/The%20Rita%20Page
This url won't work if you try to load, so it can't ripped: http://sexualsensualmenagerie.tumblr.com/tagged/The%20Rita%20Page

**Comment by 4pr0n** [comment]
The ripper uses Tumblr's API; it doesn't scrape images directly from Tumblrs (for good reason, too; tumblr pages can choose to display images/videos in very different ways/formats).

So there's no way to rip that page (a custom Tumblr page) using RipMe.

I guess the ripper could be adjusted to error if one of those "custom" pages is entered.

**Comment by Hrxn** [comment]
Just been looking at http://sexualsensualmenagerie.tumblr.com/The%20Rita%20Page

Well that is just one single page, i.e. just one chunk of HTML.
There aren't any links either, the images themselves are no links, just direct embeds.
Just <img.. elements

That means you don't need a ripper for these, you can get the direct links directly from the source.
Every decent download manager should be able to handle this.
I was always a fan of DownThemAll for Firefox, you can do it that way.

Or just copy the links from the source file. Use Regex to get the right lines.
Or just delete the first couple hundred lines, the <head and some script stuff, then delete the last part of the source, also just some scripts like Google Analytics etc.so that just the main body remains, the big bulk of <img elements.

Remove all the rest with some simple search & replace options, all the HTML markup outside of the link, so that only the real links remains, that is the content of the `src=".."`attribute in the <img tags.

You know have a simple file with just the links, and one line = one link. Then you can just feed that to `wget` ,for example. ;-)

**Comment by cm-mc** [comment]
The issue isn't specifically with that page (which you could even drag and drop from, even though that's a huge page), but ripme failing to spot tags in that case.

Btw, a possible solution could be ripme adding `/tagged/` when missing, if the url extends beyond `*.tumblr.com/`.
