### ISSUE TITLE
Not working for galleries on 500px

### ISSUE THREAD

**Issue by anonimo402** [4pr0n/ripme#282]
Galleries is the new way 500px has for curated content by the users. The old favourites have been converted now to galleries. 

The URL looks like this: https://500px.com/johnstonandjohnston/galleries/favorites

ripme returns the following message: "Expected 500px gallery formats: /stories/### /stories /favorites / Got:https://500px.com/johnstonandjohnston/galleries/favorites"

![screenshot 169](https://cloud.githubusercontent.com/assets/15182418/12008241/37742c32-ac26-11e5-8ef0-d63a5235c77e.png)

**Comment by Hrxn** [comment]
The format of the link given as input is different, hence it does not match. Not a surprise.

The links to the photo pages themselves are in the usual format (https*://500px.com/photo/< ID >/< TITLE >

So this should work with some adjustment.

But the gallery you linked here apparently has 10051 photos.
This could get interesting...

**Comment by anonimo402** [comment]
If I'm not mistaken, changing line 89 would fix the favorites
p = Pattern.compile("^.*500px.com/([a-zA-Z0-9\\-_]+)/__galleries/__favorites/?$");
adding galleries to the URL that's trying to recognize. But other galleries wouldn't work.

**Comment by Hrxn** [comment]
You know, if you refer directly to the source code, or to parts of it, like a single line, you can just do this:

https://github.com/4pr0n/ripme/blob/master/src/main/java/com/rarchives/ripme/ripper/rippers/FivehundredpxRipper.java#L89 

Makes it a lot easier and faster to find.

Here are some example links:

https://500px.com/getesmart86/galleries/d-s
https://500px.com/chrissyone/galleries/luxembourg
https://500px.com/angmel/galleries/female-beauty
https://500px.com/alexandersavov/galleries/need-for-mirrors-l-33-high-roll
https://500px.com/alisterbenn/galleries/best-of-2015
https://500px.com/thebrianwilson/galleries/star-wars

Officially curated galleries:

https://500px.com/500px/galleries/road-trip
https://500px.com/500px/galleries/minimalism
https://500px.com/500px/galleries/slow-living
https://500px.com/500px/galleries/conceptual

So the URL format is:

`https://500px.com/<USERNAME>/galleries/<GALLERYNAME>`


I think that [line](https://github.com/4pr0n/ripme/blob/master/src/main/java/com/rarchives/ripme/ripper/rippers/FivehundredpxRipper.java#L89) can be changed, and the whole block, respectively, because this old url format is not working anymore, the "favorites" feature has been replaced by the galleries as it seems.

If I go here:
http://500px.com/tsyganov/favorites
I am automatically redirected here:
https://500px.com/tsyganov/galleries

**Comment by 4pr0n** [comment]
So 500px changed their API but didn't change their API version.

I added support for `/galleries` (all galleries) and `/galleries/XXX` (subgalleries).

The "all galleries" URL is really slow since it has to fetch all photos from all galleries. Plus the ripper doesn't actually *start* the downloads until it knows all the URLs to fetch (and it finds the URLs via web requests with `sleep()`s), so it's, uh, slow.

But it should work. I found a small gallery to test on here: https://500px.com/getesmart86/galleries/olga

Issue should auto-close once the change is pushed & the new version is available.
