### ISSUE TITLE
error compiling with eroshare

### ISSUE THREAD

**Issue by kanink007** [4pr0n/ripme#313]
tried to compile the eroshare version in "pull requests". i get this error

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile 
(default-compile) on project ripme: Compilation failure
[ERROR] .../ripme-master/src/main/java/com/rarchives/ripme/utils/RipUtils.java:[85,31] cannot find symbol
[ERROR] symbol:   variable EroShareRipper
[ERROR] location: class com.rarchives.ripme.utils.RipUtils
- and btw... is this thread kind of dead? the developer wasnt online for 3 or 4 months. the one who added eroshare in pull requests registered, showed up once when posting that eroshare plugin, and never showed up again, that was 2 months ago too

**Comment by metaprime** [comment]
Really not sure which pull request this issue is referring to. Please make comments about issues with a PR on the actual PR.

I'm going to go through and merge any quality pull requests that compile and actually improve the program.

Since this tool contains a fair amount of NSFW content, many people who contribute to it use an alternate GitHub account, to keep this project from showing up on their main accounts. It's not unusual to see people show up, do a bunch of work for a little while, and then disappear because they're not thinking about developing RipMe on a regular basis.
