### ISSUE TITLE
RipMe cannot extract imgur galleries (JSON error)

### ISSUE THREAD

**Issue by AranciataExcess** [4pr0n/ripme#324]
# RipMe cannot extract imgur galleries

I believe there was a new change on Imgur that is now preventing RipMe from automatically grabbing a gallery. The logfile shows a JSON error when reading the link.
(_I am now back to doing the downloading manually via the Imgur site_).

**Example;**
_http://imgur.com/a/1SQ1p/all _  - has 107 images

RipMe runs but no images downloaded;
http://i.imgur.com/8SPnwFL.png

Ripping in RipMe ends up in an empty folder;
http://i.imgur.com/3qLKvfQ.png

**Error in logfile**
```
2016-04-22 05:31:44,486 INFO  ripper.AbstractRipper .getImgurAlbum()     Retrieving http://imgur.com/a/1SQ1p/all
2016-04-22 05:31:45,087 DEBUG ripper.AbstractRipper .getImgurAlbum() Error while parsing JSON at http://imgur.com/a/1SQ1p/all, continuing
org.json.JSONException: JSONObject["description"] not a string.
```

**Logfile attached.**

[log.txt](https://github.com/4pr0n/ripme/files/230594/log.txt)
[log.txt](https://github.com/4pr0n/ripme/files/230596/log.txt)

**Comment by ohhdemgirls** [comment]
Using `java -jar ripme.jar -u https://imgur.com/a/6aQ9F`

```
https://imgur.com/a/6aQ9F
Loaded /home/odg/downloads/rip.properties
Loaded log4j.properties
Initialized ripme v1.2.12
    Retrieving http://imgur.com/a/6aQ9F/all
[!] Falling back to /noscript method
    Retrieving http://imgur.com/a/6aQ9F/noscript
```

**Comment by iPugx** [comment]
[log.txt](https://github.com/4pr0n/ripme/files/232561/log.txt) same here

**Comment by Hrxn** [comment]
Yeah, this gallery doesn't work as usual.

You should be able to do this:
http://imgur.com/gallery/1SQ1p
instead of
http://imgur.com/a/1SQ1p

But you end up at the imgur error page..

The user link at the top of the gallery is missing as well..
Doesn't look like a normal upload.

It can be accessed via the imgur API however..
http://imgur.com/ajaxalbums/getimages/1SQ1p/hit.json?all=true

**Comment by unt0uchable** [comment]
I can confirm this is a bug in v1.2.12.

The error is in [ImgurRipper.java:230](https://github.com/4pr0n/ripme/blob/a1cb242a53bf9529b18e8cd023136ddfab4fae46/src/main/java/com/rarchives/ripme/ripper/rippers/ImgurRipper.java#L228-230) and occurs for any image without a description. When the code attempts `image.getString("description")` it fails because the value mapped to description for the image is null.

Ripme can successfully extract images that do have a description. For example, it will successfully retrieve http://imgur.com/a/tRtKF.

Perform a proactive check for null beforehand using the JsonObject.isNull(String name) method:
```
if (!image.isNull("description")) {
    description = image.getString("description");
}
```

Is it possible to downgrade until this bug is resolved?

Any ETA on when a fix can be deployed?

**Comment by 4pr0n** [comment]
Blah.

This is what happens when I stop using software I wrote.
