### ISSUE TITLE
rip from "hidden" tumblr

### ISSUE THREAD

**Issue by byefelicia** [4pr0n/ripme#340]
can anyone figure out how to rip from a "hidden" tumblr? (this question does not refer to private tumblrs, but those who are "hidden" and can only be viewed from the dashboard sidebar)

<img width="343" alt="tumblr" src="https://cloud.githubusercontent.com/assets/9995384/17279609/6e87e936-5746-11e6-965a-21967e182b43.png">

**Comment by seattle255** [comment]
That's probably more complex than simply getting the Tumblr API / ripper to work at all

**Comment by byefelicia** [comment]
it is complex and I still don't have a solution yet, but the Tumblr API should be working

**Comment by seattle255** [comment]
I haven't been seeing the Tumblr API work. Here are two attempts, right now: 

Downloading http://api.tumblr.com/v2/blog/letmedothis.tumblr.com/posts/photo?api_key=v5kUqGQXUtmF7K0itri1DGtgTs0VQpbSEbh1jxYgj9d2Sq18F8&offset=0
Rip complete, saved to /Users/Redburn2/Downloads/rips/tumblr_letmedothis.tumblr.com
Failed to load http://api.tumblr.com/v2/blog/letmedothis.tumblr.com/posts/photo?api_key=v5kUqGQXUtmF7K0itri1DGtgTs0VQpbSEbh1jxYgj9d2Sq18F8&offset=0 after 1 attempts
Downloading http://api.tumblr.com/v2/blog/thesnakeandtherabbit.tumblr.com/posts/photo?api_key=v5kUqGQXUtmF7K0itri1DGtgTs0VQpbSEbh1jxYgj9d2Sq18F8&offset=0
Rip complete, saved to /Users/Redburn2/Downloads/rips/tumblr_thesnakeandtherabbit.tumblr.com
Failed to load http://api.tumblr.com/v2/blog/thesnakeandtherabbit.tumblr.com/posts/photo?api_key=v5kUqGQXUtmF7K0itri1DGtgTs0VQpbSEbh1jxYgj9d2Sq18F8&offset=0 after 1 attempts


Do not be persuaded by the "Rip complete" lines. No rip happens because the API can't be loaded.

**Comment by rautamiekka** [comment]
The API link returns `{"meta":{"status":401,"msg":"Unauthorized"},"response":[]}`

**Comment by byefelicia** [comment]
I can rip it for you if you provide the url you wanted to rip

**Comment by seattle255** [comment]
>I can rip it for you if you provide the url you wanted to rip

Sure. letmedothis.tumblr.com, or at least the last ~six months of posts. Be forewarned it is quite large.

**Comment by metaprime** [comment]
Not sure if something has changed with that profile as far as hidden status, or maybe it's because we updated the Tumblr API key, but I am able to rip the profile you provided, and view it on the web without being logged in (although it seems to redirect to letmedothis.com when I go there in a web browser).

Can you try this with the most recent version of the software? https://github.com/4pr0n/ripme/releases

**Comment by seattle255** [comment]
Oh, brilliant, thank you. I didn't realize that 1.4.1 was out and I was using the older version. This works!

**Comment by metaprime** [comment]
@seattle255 no problem, thanks for updating! Hope you enjoy!
