### ISSUE TITLE
Instagram wrongly assicuated with IconoSquare

### ISSUE THREAD

**Issue by UnforeseenOcean** [4pr0n/ripme#342]
If, for example "https://www.instagram.com/horseman09/" was entered, it does say "Instagram Album detected."

But when I press Rip, it automatically changes to "https://iconosquare.com/horseman09/"

**Comment by UnforeseenOcean** [comment]
![image 528](https://cloud.githubusercontent.com/assets/11834016/17592257/840c97b4-601c-11e6-8960-07cbccdf3048.png)

**Comment by 0834dfbd2b** [comment]
Same as #330

**Comment by saero** [comment]
0834dbfb2b, how would one merge by oneself, and recompile?

Would it to too hard for a intermediate user who has some familiarity with programming, linux (not much atm using, including MAKE), etc?

**Comment by 0834dfbd2b** [comment]
Here is a zip with the fork created by @JoshKastang just unpack it and it works.
[Ripme.zip](https://github.com/4pr0n/ripme/files/423939/Ripme.zip)

**Comment by saero** [comment]
Good news everyone: If you use JDownloader2, they added an option to "Use original server filenames" for Instagram!

Now you can download an entire instagram or add to your existing rip of an instagram account using JD2!

I've swapped to JD2 since A) It appears RipMe won't be updated anymore except for kind souls who are forking it (bless you Josh Krang for having a fixed ripme for instagram 2 weeks ago!) and B) JDownloader2 is more heavily updated/constantly open to feedback on their forums.

https://board.jdownloader.org/showthread.php?t=70582

Check it out! I've made the swap, and also, unlike RipMe and its respective forks, JD2 downloads the CROPPED versions of images, rather than the 1080x1080 versions of images that have whitespace borders like RipMe does!

**Comment by UnforeseenOcean** [comment]
saero, please link the fixed fork here so everyone can use that instead!

**Comment by metaprime** [comment]
I've merged #336 so this issue should be fixed now.
