### ISSUE TITLE
MyHentaiComics performance improvement: start ripping ASAP

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#464]
Follow up from #454: Don't wait to parse through all pages before starting to rip the first page.

FYI @cyian-1756

**Comment by cyian-1756** [comment]
@metaprime I added ASAP ripping in [this](https://github.com/cyian-1756/ripme/tree/myhentaicomics) branch but for some reason now ripping from tags and searches ends in a `Error no images found at` error. 

I assume this is because now when ripping from tags/searches it doesn't return anything (It just downloads the albums it self)

Any idea on how I could fix it?

**Comment by metaprime** [comment]
Closed by https://github.com/4pr0n/ripme/pull/476
