### ISSUE TITLE
Submit requests for sites to support here.

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#502]
# Moved to https://github.com/RipMeApp/ripme/issues/38

# Assume all links are NSFW (unless marked SFW).

## Commenters: Please mark your NSFW links anyway.

Please open a new issue if you're reporting a problem in the ripper for a site we already support. This issue is to request support for new sites.

#### **PLEASE** include an example URL of the type of album to rip.

This issue replaces #8 which had gotten too huge to load or peruse in a reasonable amount of time.
This will give an opportunity to actually look at the older requests without new requests coming in to make that more difficult, and will help to see the more modern requests.

#510 will track received requests and aggregate links to the work in progress on each request.

Already-supported sites: https://github.com/4pr0n/ripme/wiki/Supported-Sites

**Comment by Cottoneyes** [comment]
https://purpleport.com/ has models and photographers with images, see: https://purpleport.com/portfolio/bluethealienteafairy/

**Comment by IT6uru** [comment]
VSCO

**Comment by Wiiplay123** [comment]
Deviantart, because support is currently broken. :(

**Comment by metaprime** [comment]
@IT6uru please provide example links.
@Wiiplay123 DA issues are being tracked. Limited dev-hours. Please feel free to contribute!

**Comment by LeoStaley** [comment]
Site Suggestion: http://cfake.com/ (NSFW)
Example: http://cfake.com/picture/Olivia-Munn/969

Things I've noted already that should help make implementation easier:

The actress' name is completely irrelevant. It can be changed to anything so long as the ID at the end stays the same
The first page's URL can either end after the actress' ID, or with a /p0 after the ID
Every subsequent page is specified with a /p{INTEGER}, seemingly always in increments of 30 (the number of thumbnails displayed)
Every thumbnail's IMG tag has an A tag for its parent. The link of the A tag is something like:
javascript:showimage('/big.php?show=12843193425f90a741_cfake.jpg&id_picture=97478&id_name=969&p_name=Olivia Munn','546','800')
The show parameter from the A tag's link can be appended to cfake.com/photos/ to get a direct link to the image
The site also has a "slideshow" feature which would be another (possibly easier) method to implement
The links look like this: http://cfake.com/show/Olivia%20Munn/969/p{INTEGER}#here where INTEGER is the index of the actress' pictures. (starting at 0)
This mode also seems to directly link to all images, so there would be no need to take extra steps to get the link like the other method.
It would seem that while the slideshow method as a whole would be simpler to implement, the main method would likely be faster, because only one page needs to be loaded and scraped per 30 images, as opposed to having to load an entire page for every image.
This one should be relatively easy to implement. (in comparison to some other more complicated sites)

**Comment by Marquis-deCarabas** [comment]
Two suggestions:  https://en.zenfolio.com and https://www.smugmug.com/

**Comment by Hrxn** [comment]
> Two suggestions: https://en.zenfolio.com and https://www.smugmug.com/

Good idea. Seconded.

**Comment by MrBiggz007** [comment]
Can you please add support back for OneClickChicks?  Thanks for taking this project over and continuing it!

**Comment by cyian-1756** [comment]
@MrBiggz007 Please provide example links

**Comment by gdude2002** [comment]
I see that DeviantArt albums are supported, but what about DeviantArt favourites galleries?

**Comment by MrBiggz007** [comment]
Honestly I've never used DA but I'll make an account and try it out, and get back to you
 

    On Sunday, April 23, 2017 5:23 AM, Gareth Coles <notifications@github.com> wrote:
 

 I see that DeviantArt albums are supported, but what about DeviantArt favourites galleries?—

**Comment by MrBiggz007** [comment]
OK.  It did not work on this example link
http://philosophyfetish.deviantart.com/favourites/
It says: Error: No images found at http://philosophyfetish.deviantart.com/favourites/ even though that's the page I'm on with the photos
As far as Tumblr, when you're logged in, your "likes" are under the https://www.tumblr.com/likes link, but that webpage only works on the browser when you're logged in. If you put that link into RipMe, you get the error message in my last message even if you're logged in on your browser
When you're looking at someone else's "likes" it takes their username out of the Tumblr.com part of the address - for example, where X is the username
"X.tumblr,com" is the normal homepage for a user on TumblrWhen you go to view their "likes," it turns the page address into :  www.tumblr.com/liked/by/X/   so I think RipMe is not recognizing it because the address isn't formated like "x.tumblr.com anymore" (I'm no expert in code - just trying to explain it properly)
So what I think is if RipMe can be coded to recognize the format of "www,tumblr.com/liked/by/[username]" essentially a user should be able to download their own likes as well by inputtng their own username at the end
Hope that's not confusing at all


 

    On Sunday, April 23, 2017 5:23 AM, Gareth Coles <notifications@github.com> wrote:
 

 I see that DeviantArt albums are supported, but what about DeviantArt favourites galleries?—

**Comment by metaprime** [comment]
@MrBiggz007 
> www.tumblr.com/liked/by/X/

Please provide a working example link. Every user I tried this for gives me a permission denied message.

**Comment by MrBiggz007** [comment]
Here is one that works - however, it appears you need to be logged into Tumblr to see it now that I just tried it again.  each user has the preference to turn their "Likes" public so I'm guessing the permission denied is the ones who don't have theirs public.  

https://www.tumblr.com/liked/by/hacky-gif



 

    On Tuesday, April 25, 2017 4:22 AM, metaprime <notifications@github.com> wrote:
 

 @MrBiggz007
www.tumblr.com/liked/by/X/
Please provide a working example link. Every user I tried this for gives me a permission denied message.—

**Comment by itscoldoutside** [comment]
Certain types of Eroshare links don't work ex. https://eroshare.com/14ld5ka2?
Get error "eroshare album not found in https://eroshare.com/14ld5ka2?, expected https://eroshare.com/album"

**Comment by jamedom** [comment]
could you add some more website such as http://www.porncomix.info . Thank you

**Comment by metaprime** [comment]
Example https://rule34.xxx/index.php?page=post&s=list&tags=paya_%28the_legend_of_zelda%29

**Comment by metaprime** [comment]
Another example with multiple pages: https://rule34.xxx/index.php?page=post&s=list&tags=69

**Comment by Ryalia888** [comment]
Absolutely love you guys for this application! This is going to change my life. I'm a new computer science student too.

Requesting https://www.pixiv.net/ to be supported. 

Sample links: 
https://www.pixiv.net/member.php?id=6996493 (Illustrator)
https://www.pixiv.net/member_illust.php?id=6996493 (All of an illustrator's illustrations)
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=63069362 (An illustration which may or may not include just one image or a set of images or a gif/dunno image formats)
https://www.pixiv.net/member_illust.php?mode=manga&illust_id=63069362 (An illustration or a set of illustrations)

Able to provide additional support if necessary. Would love to learn how you did this.

**Comment by metaprime** [comment]
@Ryalia888 Always happy to have more help! If you want to get started, it's best to just dive right in. Very little knowledge is necessary to get started. You can start by reading https://github.com/4pr0n/ripme/wiki/How-To-Create-A-Ripper-for-HTML-websites -- however, probably the easiest thing to do is to copy the source code from an existing Ripper that seems simple-to-understand, start a new file, and replace the code specific to the site with the code to rip from another site. You basically just need to follow the pattern already there, and use CSS-style queries to get the elements from the web page. It's sort of like a treasure hunt through the HTML to find the image URLs. There are a lot of suggestions of easy-to-implement sites on this issue and issue #8.

Let us know if you need help while implementing. Issue #510 (or a new issue you create, specific to the ripper you're working on) is a better place for that kind of discussion. You can use the Gitter chat to discuss with RipMe developers: https://gitter.im/4pr0n-ripme/Lobby.

**Comment by Flip32** [comment]
Hi, It seems Imagebam it's not working! And when does, the pics come smaller. 
Can you help me?

ex.: http://www.imagebam.com/gallery/72c5utvqv44wcqnkc9vzapm5yck8j1cr

**Comment by Flip32** [comment]
Please support for http://apina.nwps.ws

sample: http://apina.nwps.ws/realgirls/madisondeckk/

**Comment by Flip32** [comment]
Please support for http://imgbox.com/

sample: http://imgbox.com/g/9rHTTaEOjd

It works, but not with the original size

**Comment by metaprime** [comment]
xvideos gallery ripper (requested [here](https://github.com/4pr0n/ripme/issues/575#issue-234876282) by @zorb123)

**Comment by spartan9362** [comment]
Could you make a vsco.co/ ripper please it's a very good site Example: vsco.co/samdavis125 and vsco.co/samdavis125/images/1

**Comment by metaprime** [comment]
@spartan9362 That link seems broken but here's one: http://vsco.co/iamlaagan/images/1

**Comment by knusprig93** [comment]
https://luscious.net
Example:
https://luscious.net/albums/c61-nakayohi-mogudan-mogudan-ayanami-3-sensei-hen_288617/

**Comment by spartan9362** [comment]
Here's a good site could u get this one to work it's really reliable:

http://vsco.co/kellygrabowski

**Comment by cyian-1756** [comment]
@spartan9362 vsco needs javascript to work and ripme doesn't support javascript

**Comment by TriGGer20** [comment]
Why isn't anyone posting on the new site???
Smutty.com & Imagebam isn't working.

**Comment by cyian-1756** [comment]
@trigger20

> Why isn't anyone posting on the new site???

You mean the new repo? I have no idea. 

> Smutty.com & Imagebam isn't working.

I'll have to look into Imagebam. I submitted a PR to fix smutty a while back but it seems to have fallen into limbo

**Comment by TriGGer20** [comment]
@cyian-1756 Well, thanks for responding now! A fix would be very much appreciated. There seem to be no good alternative programs so I'm hoping this will be fixed soon. I'm using the new IHG as well but that doesn't work either.

**Comment by cyian-1756** [comment]
@knusprig93 I'm working on a https://luscious.net ripper I should have it done in the next few days

**Comment by cyian-1756** [comment]
@knusprig93 I've finished the https://luscious.net ripper and made a PR, it should be one of the next few updates.

**Comment by Gorthezar** [comment]
erome.com

**Comment by UnforeseenOcean** [comment]
Maybe not as new, but: 
- Shimmie based sites like https://rule34.paheal.net/
- Dutchbear (http://www.dutchbear.com) and its streaming site AEBN
- xHamster **VIDEOS**
Suggestions:
- Always try to use HTTPS over HTTP, as some countries block HTTP connections to certain sites (especially in South Korea)
- Pause ripping when disk space is getting critically low (leaving only few hundred megabytes for recycling bin)
- A PAUSE BUTTON
p.s. Is Y!Gallery ripper working? And is the site even alive anymore?

**Comment by cyian-1756** [comment]
> Shimmie based sites like https://rule34.paheal.net/

Can you provide an example album?

> Dutchbear (http://www.dutchbear.com) and its streaming site AEBN

Again example album/video please

> xHamster VIDEOS

You can use youtube-dl to download from xHamster (At least to hold you over while video support is added to ripme)

>Always try to use HTTPS over HTTP

We do, however sometimes due to poorly configured servers we have to use http (Like with xHamster)

> as some countries block HTTP connections to certain sites (especially in South Korea)

Whats to stop those countries from just block https as well? 

> Pause ripping when disk space is getting critically low (leaving only few hundred megabytes for recycling bin)

I imagine that would be a pain to implement in any cross platform manner

**Comment by rautamiekka** [comment]
^ On the contrary: https://stackoverflow.com/a/7816211/460695

Found that by `java available disk space`. It says how Java 1.7 (I think that means Java SE 7; Java always used 2 different version numbers for the same thing, as evident from [Wikipedia article](https://en.wikipedia.org/wiki/Java_version_history)) changed it from 1.6, and another answer shows it was added in 1.6 since the implementation is platform-specific.

Could've changed in 1.8 (SE 8) as well, but I didn't check any further.

**Comment by UnforeseenOcean** [comment]
^^
1. Examples for Rule34?
Try https://rule34.paheal.net/post/list/Baradok/1

2. Examples for Dutchbear? 
Unfortunately it works a little bit different from other sites (it's more like a collection of images and not quite a make-a-profile-and-upload-stuff-there business), and AEBN is blocked here so I can't provide examples. However, I can provide a page link, like this one: http://pictures.dutchbear.com/feature/realmen/real4/realmen34.html

3. Use youtube-dl for xHamster duty
Sure, I will check. I needed a freeware solution to the one I used previously, anyway.

4. It depends on the case
Understood.

5. Why are they not blocking HTTPS in the first place?
I dunno, but it's pretty stupid anyway.

6. Disk use alarm is kind of tough thing to deal with, when taking multi-platform into consideration
There indeed is a way to do so without breaking compatibility with Linux and OSX (as shown by rautamiekka), but then they will not be compatible with older versions of Java.

**Comment by rautamiekka** [comment]
^ There are no reasons to use so old Java anyway; 1.6 == SE 6, 1.7 == SE 7, and so on. If any, such are something like 1 in a billion, to put into a perspective.

**Comment by cyian-1756** [comment]
> On the contrary: https://stackoverflow.com/a/7816211/460695

Neat. If we do implement it it should be a option tho. Scanning / on some set ups (NASs come to mind) will take a great deal of time/cause all discs to spin up

**Comment by cyian-1756** [comment]
@UnforeseenOcean It seems that https://rule34.paheal.net/ is already supported, did you mean generic support for sites that use the same software? If so can link me to that software source/other sites that use it?

**Comment by UnforeseenOcean** [comment]
@cyian-1756 Yes. Looks like Danbooru pages use some sort of forked source of Shimmie. I don't know a lot about sites utilizing such library, but I think most of them work in the same way.

**Comment by cyian-1756** [comment]
@UnforeseenOcean I'll get on adding generic support for Shimmie

**Comment by tjlsmith** [comment]
Hi. This site http://www.aerisdies.com has a remarkable selection of Doujin... Like this http://www.aerisdies.com/html/lb/douj_s369.html

Thank you for this dream piece of software.

**Comment by cyian-1756** [comment]
@tjlsmith I added support for http://www.aerisdies.com in my latest commit, it should be ripme in the next update or so

**Comment by rautamiekka** [comment]
@gdude2002 DeviantArt support is mostly perfect: you can rip
1) specific folders from both the gallery and favs (it can't distinguish between them)
2) the 'Featured' section from both gallery and favs (example=)
3) 'All' link from both gallery and favs to get everything (examples=), but that way you won't get them in their folders
4) scraps

What doesn't work at the time of writing this:
1) avatar fetching (always fails with an incorrect path): https://github.com/4pr0n/ripme/issues/577
2) recursive ripping, meaning auto-walking folders as they come, putting stuff in the folders as they appear: https://github.com/4pr0n/ripme/issues/550
3) the favs folder address parsing has an unreported bug I found that shows up only in specific cases

**Comment by rautamiekka** [comment]
http://philosophyfetish.deviantart.com/favourites/ ripped perfectly with DA's expectable delay.

**Comment by gdude2002** [comment]
That's excellent, thanks for letting me know @rautamiekka

**Comment by tim712** [comment]
Hello,
Can you add support for book.fr
https://lolajrenault.book.fr

thanks

**Comment by Michael9450** [comment]
Could there be support for http://hgamecg.com/ . If anyone can do this that would be great but thanks anyway.

**Comment by wankio** [comment]
Site Suggestion: http://www.bobx.com/  (NSFW)
http://www.bobx.com/dark/ | http://www.bobx.com/av-idol/index_all_pictures.html | v.v..etc...
all will end up with http://www.bobx.com/av-idol/[name]

Example: http://www.bobx.com/av-idol/ruru-anoa/ 

Each av-idol have photosets : 
Example : http://www.bobx.com/av-idol/ruru-anoa/photoset/graphis-gals-_194---exclaiming-0-2-8.html

Photos link : http://www.bobx.com/av-idol/ruru-anoa/large-ruru-anoa-471704/
DDL when clicked on HI-RES (if available) : http://www.bobx.com/av-idol/ruru-anoa/large-ruru-anoa-471704/ -> http://www.bobx.com/av-idol/ruru-anoa/ruru-anoa-00471704.jpg

What i want is download all images from photoset link and rename to <title> 
Example : Ruru Anoa in Graphis Gals #194 - Exclaiming - @0 of 96

Thank

**Comment by RahulJanagouda** [comment]
Pinterest?? anyone

**Comment by tjlsmith** [comment]
https://voat.co/v/FarmGirls

voat.co in general, really - it should be like Reddit...

**Comment by lucasporlier** [comment]
On the SFW side, commons.wikimedia.org, with metadata options if doable

**Comment by metaprime** [comment]
@tjlsmith about Voat.co: I wonder if there's actually any difference between that site and Reddit. It might be using Reddit's front-end code (as of some point in the past), in which case, our Reddit ripper may already support it, or a slightly modified version of it would do the job.

**Comment by metaprime** [comment]
@wankio bobx.com/dark is great -- it's actually how I found my first content download accelerator (DownThemAll Firefox add-on), and then promptly got IP banned for "spidering" aka making too many requests too quickly. Since I've got experience with that one I'll probably make the ripper, but we'll have to be careful to make the delay long enough to avoid getting users banned.

**Comment by metaprime** [comment]
Please post new requests at RipMeApp/ripme#38

**Comment by OwlDragon** [comment]
Please could yo add pixiv.net support

**Comment by Aderski47** [comment]
Any chance to add support for sex.com
please :)

**Comment by DipayanDey** [comment]
http://demo.modelnet.club/

Studio Manager area:
http://demo.modelnet.club/exec/manager/
Login: admin
Password: admin

Performers area:
http://demo.modelnet.club/exec/performer/index.jsp
Login: model
Password: model

Client area:
http://demo.modelnet.club/exec/

other site is with same features 
http://demo.online-webcam.net/

**Comment by DJboutit** [comment]
Please add https://coomer.party/
